declare let GLOBAL : any;
declare let NOTIFY : {
    FORGOT_PASSWORD : string;
    REGISTERED : string;
    ERROR_SOCIAL_LOGIN : string;
    RESET_PASSWORD : string;
    UPLOAD_PROFILE : string;
};
declare let CONTROLLER : {
    LISTING_FORM_IS_LOADING : string;
    LISTING_FORM_IS_DONE : string;
}
declare let STEPS : {
    STEP1 : string;
    STEP2 : string;
    STEP3 : string;
    STEP4 : string;
    UNSAVED : string;
    SAVED_OR_DISCARD : string;
    UNSAVED_REDIRECT : string;
}
declare let NOTIFICATIONS : {
    REQUEST_NOTIFICATION_SEEN : string;
    REQUEST_NOTIFICATION_UNSEEN : string;
}

declare let ERROR : {
    TOKEN_EXPIRED : string;
}

namespace('NOTIFY').REGISTERED = 'NOTIFY.REGISTERED';
namespace('NOTIFY').ERROR_SOCIAL_LOGIN = 'NOTIFY.ERROR_SOCIAL_LOGIN';
namespace('NOTIFY').FORGOT_PASSWORD = 'NOTIFY.FORGOT_PASSWORD';
namespace('NOTIFY').RESET_PASSWORD = 'NOTIFY.RESET_PASSWORD';
namespace('NOTIFY').UPLOAD_PROFILE = 'NOTIFY.UPLOAD_PROFILE';

namespace('CONTROLLER').LISTING_FORM_IS_LOADING = 'CONTROLLER.LISTING_FORM_IS_LOADING';
namespace('CONTROLLER').LISTING_FORM_IS_DONE = 'CONTROLLER.LISTING_FORM_IS_DONE';

namespace('STEPS').STEP1 = 'STEPS.STEP1';
namespace('STEPS').STEP1 = 'STEPS.STEP2';
namespace('STEPS').STEP1 = 'STEPS.STEP3';
namespace('STEPS').STEP1 = 'STEPS.STEP4';
namespace('STEPS').UNSAVED = 'STEPS.UNSAVED';
namespace('STEPS').SAVED_OR_DISCARD = 'STEPS.SAVED_OR_DISCARD';
namespace('STEPS').UNSAVED_REDIRECT = 'STEPS.UNSAVED_REDIRECT';

namespace('NOTIFICATIONS').REQUEST_NOTIFICATION_SEEN = 'NOTIFICATIONS.REQUEST_NOTIFICATION_SEEN';
namespace('NOTIFICATIONS').REQUEST_NOTIFICATION_UNSEEN = 'NOTIFICATIONS.REQUEST_NOTIFICATION_UNSEEN';

namespace('ERROR').TOKEN_EXPIRED = 'ERROR.TOKEN_EXPIRED';